org.gradle.jvmargs=-Xmx2g
systemProp.http.proxyHost=hatch-egress-proxy
systemProp.http.proxyPort=3128
systemProp.http.proxyUser=hatch-runtime
systemProp.http.proxyPassword=de484b6fcd044f2f81faee0975076fc6
systemProp.http.nonProxyHosts=localhost|127.0.0.1
systemProp.https.proxyHost=hatch-egress-proxy
systemProp.https.proxyPort=3128
systemProp.https.proxyUser=hatch-runtime
systemProp.https.proxyPassword=de484b6fcd044f2f81faee0975076fc6
systemProp.https.nonProxyHosts=localhost|127.0.0.1
